[mypy]
python_version = 3.12
ignore_missing_imports = True
disallow_untyped_defs = False
warn_unused_ignores = True
warn_redundant_casts = True
exclude = (?x)(
    app/tests/
    | app/db/migrations/
  )

[mypy-playwright.*]
ignore_missing_imports = True

[mypy-selenium.*]
ignore_missing_imports = True

[mypy-groq.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True
